# Generated by Django 5.0.2 on 2024-02-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Glocuse', models.FloatField(max_length=10)),
                ('BMI', models.FloatField(max_length=10)),
                ('Pressure', models.FloatField(max_length=10)),
            ],
        ),
    ]
